### ISSUE TITLE
Drafts: Invalid request error / not implemented when trying to use Drafts.update/4.

### ISSUE THREAD

**Issue by crova** [nicholasbair/ex_nylas#237]
Hello there. 
First of all, thanks for the amazing work on this library. It makes things much easier when integrating with Nylas.

I'm trying to integrate drafts into our application and I'm having a hard time updating them with attachments.

`Drafts.update/3` works as expected:

```elixir
args = %{body: "", to: [%{email: "crova@email.com"}], subject: "Subject"}
{:ok, draft} = N.create_draft(grant, args, [])
{:ok,
 %ExNylas.Common.Response{
   request_id: "request id",
   status: :ok,
   data: %ExNylas.Draft{
     id: "someid"
   },
   next_cursor: nil,
   error: nil
 }}
{:ok, draft} = N.update_draft(grant, draft.data.id, args)
{:ok,
 %ExNylas.Common.Response{
   request_id: "request id",
   status: :ok,
   data: %ExNylas.Draft{
     id: "someid"
   },
   next_cursor: nil,
   error: nil
 }}
```

But `Drafts.update/4` keeps throwing an error:

```elixir
args = %{body: "", to: [%{email: "crova@email.com"}], subject: "Subject"}
files1 = ["temp_file1.png"] 
{:ok, draft} = N.create_draft(grant, args, [])
{:ok,
 %ExNylas.Common.Response{
   request_id: "request id",
   status: :ok,
   data: %ExNylas.Draft{
     id: "someid"
   },
   next_cursor: nil,
   error: nil
 }}
{:ok, draft} = N.update_draft(grant, draft.data.id, args, files1)
** (MatchError) no match of right hand side value: 
{:error, %ExNylas.Common.Response{request_id: nil, status: :not_implemented, data: nil, next_cursor: nil, 
error: %ExNylas.Common.Error{type: "invalid_request_error", message: "NOT IMPLEMENTED", provider_error: nil}}}
```

I can create drafts with attachments.

```elixir
args = %{body: "", to: [%{email: "crova@email.com"}], subject: "Subject"}
files1 = ["temp_file1.png"] 
{:ok, draft} = N.create_draft(g, args, files1)
{:ok,
 %ExNylas.Common.Response{
   request_id: "request id",
   status: :ok,
   data: %ExNylas.Draft{
     id: "draft id",
     grant_id: "grant id",
     object: "draft",
     thread_id: nil,
     reply_to_message_id: nil,
     date: nil,
     snippet: nil,
     starred: nil,
     subject: "Subject",
     body: nil,
     folders: nil,
     attachments: [
       %ExNylas.Attachment{
         id: "some id",
         grant_id: nil,
         content_type: "image/png",
         size: 92285,
         filename: "temp_file1.png",
         is_inline: nil
       }
     ],
     bcc: [],
     cc: [],
     from: [
       %ExNylas.Common.EmailParticipant{
         email: "crova@email.com",
         name: nil
       }
     ],
     reply_to: [],
     to: [
       %ExNylas.Common.EmailParticipant{
         email: "crova@email.com",
         name: nil
       }
     ],
     tracking_options: nil
   },
   next_cursor: nil,
   error: nil
 }}
```

But it also fails when trying to update the draft with more attachments.

If I create a draft with attachments, call `update/3`, it removes all the attachmens as expected, but when calling `update/4`, it fails again.

Am I doing something clearly wrong here?
I'll gladly provide more information on this if needed. I truncated the responses just to there is less clutter (except the one with the attachments).

Please note that `create_draft` and `update_draft` are just wrappers around `Draft.create/update` with a function call to build the `conn`.

Thanks again for the great work on this library.

**Comment by Jayme-T** [comment]
@crova thanks for raising this. @nicholasbair the owner of this sdk got ahold of me because I work at Nylas and it appears this is an underlying Nylas issue not an issue with the sdk itself. I am working to get this escalated so appreciate you raising it. If you want updates directly from Nylas about when this and when it is done let me know the best way to connect you or anyone on your team/org. Thanks

**Comment by neilberkman** [comment]
Hi @Jayme-T I work with @crova. Our account is under enaia.co. Thanks.

**Comment by crova** [comment]
Thanks for getting back to me so quickly @Jayme-T . I appreciate the feedback.
As @neilberkman mentioned, the account under enaia.co would be the best way.

@nicholasbair should we close this then?

**Comment by nicholasbair** [comment]
Hey @crova, yes, I'll proceed with closing this out.  Thanks for your kind words, please don't hesitate to reach out with any future issues or feedback!
