### ISSUE TITLE
Draft update: attachment encoding issue

### ISSUE THREAD

**Issue by neilberkman** [nicholasbair/ex_nylas#285]
@nicholasbair we're experiencing the issue below. I realize it may be an issue in the API itself but reporting it here in case it is an issue with the library.

## Description

When using the Nylas API to work with draft emails and attachments:
- Creating a draft with an attachment via the `create` draft API works as expected.
- Updating a draft with an attachment via the `update` draft API appears to work, but the resulting attachment is base64 encoded.

## Steps To Reproduce

1. Run the script, after filling in the credentials:

```elixir
Mix.install([
  {:ex_nylas, github: "nicholasbair/ex_nylas"}
])

grant_id = "...fill me..."
client_id = "...fill me..."
api_key = "...fill me..."

conn = %ExNylas.Connection{
  client_id: client_id,
  api_key: api_key,
  grant_id: grant_id
}

args = %{
  body: "<b>Example</b>",
  to: [%{email: "me@marc-andre.ca", name: "Me"}],
  subject: "Example"
}

file_path = Path.join(System.tmp_dir!(), "example.txt")
File.write!(file_path, "Example content")

file_path_2 = Path.join(System.tmp_dir!(), "example2.txt")
File.write!(file_path_2, "Second example")

response = ExNylas.Drafts.create(conn, args, [file_path])
{:ok, %{data: %{id: draft_id}}} = response

response2 = ExNylas.Drafts.update(conn, draft_id, args, [file_path_2])

dbg({response, response2})
```

2. Check your email client (e.g., Outlook) for the draft email that was created.

3. Open the draft email and download both attachments.

4. Examine the contents of both downloaded attachments:
    - The first attachment (from the `create` operation) should contain "Example content" in plain text.
    - The second attachment (from the `update` operation) should contain "Second example", but it may be base64 encoded.

## Expected Behavior

Both attachments (from `create` and `update` operations) should be identical in encoding and directly readable as plain text.

## Actual Behavior

- The attachment from the `create` operation is as expected (plain text).
- The attachment from the `update` operation is base64 encoded.

**Comment by nicholasbair** [comment]
Hey @neilberkman thanks for reaching out.  Unfortunately, I was able to duplicate this by calling the REST API directly, so as far as I can tell, its an issue with the underlying API.  If you haven't already, I suggest reaching out to Nylas support (either via email: `support@nylas.com` or via the support portal `support.nylas.com`.

**Comment by neilberkman** [comment]
Thanks @nicholasbair we have reached out. Appreciate you checking into this.
