### ISSUE TITLE
Attachment content types and content id

### ISSUE THREAD

**Issue by marcandre** [nicholasbair/ex_nylas#286]
Hi!

I'm trying to add attachments to drafts for @neilberkman, and want to have inline images with content id.

1) From the source code, I'm deducing that I should be passing `{content_id, file_path}` for such an attachment, right? I didn't see this documented, so is this official?

2) It doesn't seem possible to pass the content type, i.e. no calls to `Multipart.Part.file_content_field` have a `content_type` option. Is that planned?

Maybe having a struct for attachments would be more future proof  (with automatic conversion of `path when is_binary(path)` to `%ExNylas.Attachment{path: path}`). Let me know if you'd like a PR.

Thank you

**Comment by nicholasbair** [comment]
Hey @marcandre, thanks for reaching out.

1. That's correct, for inline attachments you would pass a list of tuples with the CID and file path, e.g. `[{cid, path}, ...]`.
2. Explicitly passing the content type wasn't something that's on my radar.  IIRC, Multipart detects the mime type based on the file.  Out of curiosity, why would you want/need to explicitly set it?

Thanks!

**Comment by marcandre** [comment]
Thanks for the quick reply.

2. Well, it doesn't work currently, my image is not treated as such, but that might be because of the `Drafts.update` bug. Or because I strip the filename extension, so I'll try keeping it around.

Thanks
